CREATE TABLE IF NOT EXISTS account (
    id BIGINT PRIMARY KEY,
    balance DECIMAL(19, 2),
    currency VARCHAR(3) DEFAULT 'HKD',
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);